// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using health_consulting_website.Models;

#nullable disable

namespace health_consulting_website.Migrations
{
    [DbContext(typeof(ConsultContext))]
    partial class ConsultContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("health_consulting_website.Models.BacSi", b =>
                {
                    b.Property<string>("SMaBacSi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sMaBacSi");

                    b.Property<double?>("FPriceConsult")
                        .HasColumnType("float")
                        .HasColumnName("fPriceConsult");

                    b.Property<int?>("IntNamSinh")
                        .HasColumnType("int")
                        .HasColumnName("intNamSinh");

                    b.Property<string>("SAvatar")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sAvatar");

                    b.Property<string>("SMaChuyenKhoa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sMaChuyenKhoa");

                    b.Property<string>("SMaDonViCongTac")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sMaDonViCongTac");

                    b.Property<string>("SMaTaiKhoan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sMaTaiKhoan");

                    b.Property<string>("STenBacSi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sTenBacSi");

                    b.Property<string>("SmMoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("smMoTa");

                    b.HasKey("SMaBacSi")
                        .HasName("PK__BacSi__E470D536E8EE2067");

                    b.HasIndex(new[] { "SMaChuyenKhoa" }, "IX_BacSi_sMaChuyenKhoa");

                    b.HasIndex(new[] { "SMaDonViCongTac" }, "IX_BacSi_sMaDonViCongTac");

                    b.HasIndex(new[] { "SMaTaiKhoan" }, "IX_BacSi_sMaTaiKhoan");

                    b.ToTable("BacSi", (string)null);
                });

            modelBuilder.Entity("health_consulting_website.Models.BangThoiGianTuVan", b =>
                {
                    b.Property<string>("SMaThoiGianTuVan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sMaThoiGianTuVan");

                    b.Property<TimeOnly?>("TThoiGianBatDau")
                        .HasColumnType("time")
                        .HasColumnName("tThoiGianBatDau");

                    b.Property<TimeOnly?>("TThoiGianKetThuc")
                        .HasColumnType("time")
                        .HasColumnName("tThoiGianKetThuc");

                    b.HasKey("SMaThoiGianTuVan")
                        .HasName("PK__BangThoi__3FCAB332587359FD");

                    b.ToTable("BangThoiGianTuVan", (string)null);
                });

            modelBuilder.Entity("health_consulting_website.Models.ChuyenKhoa", b =>
                {
                    b.Property<string>("SMaChuyenKhoa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sMaChuyenKhoa");

                    b.Property<string>("SMota")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sMota");

                    b.Property<string>("STenChuyenKhoa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sTenChuyenKhoa");

                    b.Property<string>("Sthumbnail")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sthumbnail");

                    b.HasKey("SMaChuyenKhoa")
                        .HasName("PK__ChuyenKh__45D83D3432358F3B");

                    b.ToTable("ChuyenKhoa", (string)null);
                });

            modelBuilder.Entity("health_consulting_website.Models.DonViCongTac", b =>
                {
                    b.Property<string>("SMaDonVi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sMaDonVi");

                    b.Property<string>("STenDonVi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sTenDonVi");

                    b.HasKey("SMaDonVi")
                        .HasName("PK__DonViCon__17898EE8908AF687");

                    b.ToTable("DonViCongTac", (string)null);
                });

            modelBuilder.Entity("health_consulting_website.Models.NguoiDung", b =>
                {
                    b.Property<string>("SMaNguoiDung")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sMaNguoiDung");

                    b.Property<string>("BGioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("bGioiTinh");

                    b.Property<DateOnly?>("DNgaySinh")
                        .IsRequired()
                        .HasColumnType("date")
                        .HasColumnName("dNgaySinh");

                    b.Property<string>("SHoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sHoTen");

                    b.Property<string>("SMaTaiKhoan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sMaTaiKhoan");

                    b.Property<string>("SSdt")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("sSDT");

                    b.Property<string>("SmDiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("smDiaChi");

                    b.HasKey("SMaNguoiDung")
                        .HasName("PK__NguoiDun__47E09BE3839AF2D6");

                    b.HasIndex(new[] { "SMaTaiKhoan" }, "IX_NguoiDung_sMaTaiKhoan");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("health_consulting_website.Models.Quyen", b =>
                {
                    b.Property<string>("SMaQuyen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sMaQuyen");

                    b.Property<string>("STenQuyen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sTenQuyen");

                    b.HasKey("SMaQuyen")
                        .HasName("PK__Quyen__0A7BEA5FD9F2B2CC");

                    b.ToTable("Quyen", (string)null);
                });

            modelBuilder.Entity("health_consulting_website.Models.Session", b =>
                {
                    b.Property<string>("SSessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sSessionId");

                    b.Property<DateTime>("DExpireTime")
                        .HasColumnType("datetime")
                        .HasColumnName("dExpireTime");

                    b.Property<string>("SSessionData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sSessionData");

                    b.HasKey("SSessionId")
                        .HasName("PK__Session__138F9F35E2658B1B");

                    b.ToTable("Session", (string)null);
                });

            modelBuilder.Entity("health_consulting_website.Models.TaiKhoan", b =>
                {
                    b.Property<string>("SMaTaiKhoan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sMaTaiKhoan");

                    b.Property<string>("SMaQuyen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sMaQuyen");

                    b.Property<string>("SMatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sMatKhau");

                    b.Property<string>("STenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sTenDangNhap");

                    b.HasKey("SMaTaiKhoan")
                        .HasName("PK__TaiKhoan__0387828823E60E44");

                    b.HasIndex(new[] { "SMaQuyen" }, "IX_TaiKhoan_sMaQuyen");

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("health_consulting_website.Models.TrangThaiTuVan", b =>
                {
                    b.Property<string>("SMaTrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sMaTrangThai");

                    b.Property<string>("SMoTaTrangThai")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sMoTaTrangThai");

                    b.Property<string>("STenTrangThai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sTenTrangThai");

                    b.HasKey("SMaTrangThai")
                        .HasName("PK__TrangTha__C99ADF4E323444D8");

                    b.ToTable("TrangThaiTuVan", (string)null);
                });

            modelBuilder.Entity("health_consulting_website.Models.TuVan", b =>
                {
                    b.Property<string>("SMaLich")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sMaLich");

                    b.Property<DateOnly?>("DNgayTuVan")
                        .HasColumnType("date")
                        .HasColumnName("dNgayTuVan");

                    b.Property<string>("SMaBacSi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sMaBacSi");

                    b.HasKey("SMaLich")
                        .HasName("PK__TuVan__6D2B2A52143386AE");

                    b.HasIndex(new[] { "SMaBacSi" }, "IX_TuVan_sMaBacSi");

                    b.ToTable("TuVan", (string)null);
                });

            modelBuilder.Entity("health_consulting_website.Models.TuVanBangThoiGian", b =>
                {
                    b.Property<string>("SMaLich")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sMaLich");

                    b.Property<string>("SMaThoiGianTuVan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sMaThoiGianTuVan");

                    b.Property<int?>("IDanhGia")
                        .HasColumnType("int")
                        .HasColumnName("iDanhGia");

                    b.Property<string>("SGhiChuBacSi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sGhiChuBacSi");

                    b.Property<string>("SGhiChuNguoiDuocTuVan")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sGhiChuNguoiDuocTuVan");

                    b.Property<string>("SMaNguoiDung")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sMaNguoiDung");

                    b.Property<string>("SMaTrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sMaTrangThai");

                    b.HasKey("SMaLich", "SMaThoiGianTuVan")
                        .HasName("PK__TuVan_Ba__5ED7816151539FE3");

                    b.HasIndex("SMaNguoiDung");

                    b.HasIndex("SMaTrangThai");

                    b.HasIndex(new[] { "SMaThoiGianTuVan" }, "IX_TuVan_BangThoiGian_sMaThoiGianTuVan");

                    b.ToTable("TuVan_BangThoiGian", (string)null);
                });

            modelBuilder.Entity("health_consulting_website.Models.BacSi", b =>
                {
                    b.HasOne("health_consulting_website.Models.ChuyenKhoa", "SMaChuyenKhoaNavigation")
                        .WithMany("BacSis")
                        .HasForeignKey("SMaChuyenKhoa")
                        .HasConstraintName("FK__BacSi__sMaChuyen__1BFD2C07");

                    b.HasOne("health_consulting_website.Models.DonViCongTac", "SMaDonViCongTacNavigation")
                        .WithMany("BacSis")
                        .HasForeignKey("SMaDonViCongTac")
                        .HasConstraintName("FK__BacSi__sMaDonViC__1DE57479");

                    b.HasOne("health_consulting_website.Models.TaiKhoan", "SMaTaiKhoanNavigation")
                        .WithMany("BacSis")
                        .HasForeignKey("SMaTaiKhoan")
                        .HasConstraintName("FK__BacSi__sMaTaiKho__1CF15040");

                    b.Navigation("SMaChuyenKhoaNavigation");

                    b.Navigation("SMaDonViCongTacNavigation");

                    b.Navigation("SMaTaiKhoanNavigation");
                });

            modelBuilder.Entity("health_consulting_website.Models.NguoiDung", b =>
                {
                    b.HasOne("health_consulting_website.Models.TaiKhoan", "SMaTaiKhoanNavigation")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("SMaTaiKhoan")
                        .HasConstraintName("FK__NguoiDung__sMaTa__15502E78");

                    b.Navigation("SMaTaiKhoanNavigation");
                });

            modelBuilder.Entity("health_consulting_website.Models.TaiKhoan", b =>
                {
                    b.HasOne("health_consulting_website.Models.Quyen", "SMaQuyenNavigation")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("SMaQuyen")
                        .HasConstraintName("FK__TaiKhoan__sMaQuy__1273C1CD");

                    b.Navigation("SMaQuyenNavigation");
                });

            modelBuilder.Entity("health_consulting_website.Models.TuVan", b =>
                {
                    b.HasOne("health_consulting_website.Models.BacSi", "SMaBacSiNavigation")
                        .WithMany("TuVans")
                        .HasForeignKey("SMaBacSi")
                        .HasConstraintName("FK__TuVan__sMaBacSi__25869641");

                    b.Navigation("SMaBacSiNavigation");
                });

            modelBuilder.Entity("health_consulting_website.Models.TuVanBangThoiGian", b =>
                {
                    b.HasOne("health_consulting_website.Models.TuVan", "SMaLichNavigation")
                        .WithMany("TuVanBangThoiGians")
                        .HasForeignKey("SMaLich")
                        .IsRequired()
                        .HasConstraintName("FK__TuVan_Ban__sMaLi__2A4B4B5E");

                    b.HasOne("health_consulting_website.Models.NguoiDung", "SMaNguoiDungNavigation")
                        .WithMany("TuVanBangThoiGians")
                        .HasForeignKey("SMaNguoiDung")
                        .HasConstraintName("FK__TuVan_Ban__sMaNg__2B3F6F95");

                    b.HasOne("health_consulting_website.Models.BangThoiGianTuVan", "SMaThoiGianTuVanNavigation")
                        .WithMany("TuVanBangThoiGians")
                        .HasForeignKey("SMaThoiGianTuVan")
                        .IsRequired()
                        .HasConstraintName("FK__TuVan_Ban__sMaTh__2B3F6F97");

                    b.HasOne("health_consulting_website.Models.TrangThaiTuVan", "SMaTrangThaiNavigation")
                        .WithMany("TuVanBangThoiGians")
                        .HasForeignKey("SMaTrangThai")
                        .HasConstraintName("FK__TuVan_Ban__sMaTrangT__276EDEB3");

                    b.Navigation("SMaLichNavigation");

                    b.Navigation("SMaNguoiDungNavigation");

                    b.Navigation("SMaThoiGianTuVanNavigation");

                    b.Navigation("SMaTrangThaiNavigation");
                });

            modelBuilder.Entity("health_consulting_website.Models.BacSi", b =>
                {
                    b.Navigation("TuVans");
                });

            modelBuilder.Entity("health_consulting_website.Models.BangThoiGianTuVan", b =>
                {
                    b.Navigation("TuVanBangThoiGians");
                });

            modelBuilder.Entity("health_consulting_website.Models.ChuyenKhoa", b =>
                {
                    b.Navigation("BacSis");
                });

            modelBuilder.Entity("health_consulting_website.Models.DonViCongTac", b =>
                {
                    b.Navigation("BacSis");
                });

            modelBuilder.Entity("health_consulting_website.Models.NguoiDung", b =>
                {
                    b.Navigation("TuVanBangThoiGians");
                });

            modelBuilder.Entity("health_consulting_website.Models.Quyen", b =>
                {
                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("health_consulting_website.Models.TaiKhoan", b =>
                {
                    b.Navigation("BacSis");

                    b.Navigation("NguoiDungs");
                });

            modelBuilder.Entity("health_consulting_website.Models.TrangThaiTuVan", b =>
                {
                    b.Navigation("TuVanBangThoiGians");
                });

            modelBuilder.Entity("health_consulting_website.Models.TuVan", b =>
                {
                    b.Navigation("TuVanBangThoiGians");
                });
#pragma warning restore 612, 618
        }
    }
}
